/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_material_travel_GuideJNI */

#ifndef _Included_com_material_travel_LoginActivity
#define _Included_com_material_travel_LoginActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_material_travel_LoginActivity
 * Method:    gennerateStrFromNative
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_material_travel_LoginActivity_gennerateStrFromNative
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_material_travel_LoginActivity
 * Method:    getStrFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_material_travel_LoginActivity_getStrFromNative
  (JNIEnv *, jclass);

/*
 * Class:     com_material_travel_LoginActivity
 * Method:    invokeMthod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_material_travel_LoginActivity_invokeMthod
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
